blank_issues_enabled: false
contact_links:
  - name: ğŸ“•Contributing Guides
    url: https://github.com/lumirlumir/npm-textlint-rule-allowed-uris?tab=readme-ov-file#contributing
    about: Contributing Guides for textlint-rule-allowed-uris.
  - name: ğŸ“—Textlint Guides
    url: https://textlint.github.io
    about: Textlint Guides.
  - name: ğŸ“˜AST Tree for textlint
    url: https://textlint.github.io/astexplorer
    about: AST Tree for textlint.
